ais/ais/urls.py
from django.conf import settings
from django.conf.urls import (
    url,
    include,
)
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

from profiles import urls as profiles_url
from odocs import urls as odocs_url
from dashboard.views import DashBoardView
from . import urls_api

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profiles/', include((profiles_url, 'profiles'), namespace='profiles')),
    url(r'^dashboard/$', DashBoardView.as_view(), name='dashboard'),
    url(r'^odocs/', include((odocs_url, 'odocs'), namespace='odocs')),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
    url(r'^api/', include((urls_api, 'api'), namespace='api')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

ais/odocs/api/urls.py
from django.conf.urls import url, include
from rest_framework import routers

from . import views as views


urlpatterns = [
    url(r'^$', views.OdocListAPIView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)$', views.OdocDetailAPIView.as_view(), name='detail'),
    url(r'^create$', views.OdocCreateAPIView.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/edit$', views.OdocUpdateAPIView.as_view(), name='edit'),
    url(r'^(?P<pk>\d+)/delete$', views.OdocDeleteAPIView.as_view(), name='delete'),
    url(r'^odoctypes$', views.OdocTypeListAPIView.as_view(), name='odoc_type_list'),
]

ais/odocs/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.ListOdoc.as_view(), name='list'),
    url(r'^create/$', views.CreateOdoc.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/delete/$', views.DeleteOdoc.as_view(), name='delete'),
    url(r'^(?P<pk>\d+)/$', views.EditOdoc.as_view(), name='edit'),
]

ais/odocs/models.py
from django.db import models
from ckeditor.fields import RichTextField

from documents.models import (
    BaseModelDocument,
    Document,
)
from docflows.models import DocPath
from docflows.mixins import DocflowMixin


class OdocType(models.Model):
    title = models.TextField(max_length=100, verbose_name='Тип служебной записки')
    doc_path = models.ForeignKey(DocPath, on_delete=models.PROTECT)

    def __str__(self):
        return self.title


class Odoc(DocflowMixin, BaseModelDocument):
    DOCTYPE_NAME = 'ODOC'
    text = RichTextField(verbose_name='Содержание')
    document = models.OneToOneField(
        Document,
        on_delete=models.CASCADE,
    )
    odoc_type = models.ForeignKey(OdocType, on_delete=models.PROTECT)

    class Meta:
        ordering = ('-document__changed_at', '-document__created_at', )

    def __str__(self):
        return 'Odoc pk={} {}'.format(self.pk, self.odoc_type.title)

    @property
    def doc_path(self):
        return self.odoc_type.doc_path

ais/odocs/forms.py
from ckeditor.widgets import CKEditorWidget
from django import forms
from .models import (
    Odoc,
    OdocType,
)
from documents.models import Document
from documents.forms import DocumentForm


class OdocForm(DocumentForm):
    text = forms.CharField(
        widget=CKEditorWidget(),
        error_messages={'required': 'Введите текст служебной записки!'},
        label='Текст',
    )

    odoc_type = forms.ModelChoiceField(
        queryset=OdocType.objects.all(),
        label='Тип служебной записки',
    )

    class Meta:
        model = Odoc
        fields = ('odoc_type', 'text')

ais/odocs/api/views.py
from rest_framework import filters
from rest_framework.generics import (
    ListAPIView,
    RetrieveAPIView,
    CreateAPIView,
    UpdateAPIView,
    DestroyAPIView,
)

from odocs.models import Odoc
from odocs.models import OdocType
from odocs.models import Document

from .serializers import (
    OdocSerializer,
    OdocEditSerializer,
    OdocListSerializer,
    OdocTypeSerializer,
)
from .pagination import OdocLimitOffsetPagination
from documents.api.pagination import DocumentPageNumberPagination


class OdocTypeListAPIView(ListAPIView):
    queryset = OdocType.objects.all()
    serializer_class = OdocTypeSerializer


class OdocListAPIView(ListAPIView):
    """
    API endpoint that allowed odocs documents to be list view.
    """
    # queryset = Odoc.objects.all()
    serializer_class = OdocListSerializer
    pagination_class = DocumentPageNumberPagination
    filter_backends = (filters.SearchFilter, filters.OrderingFilter)
    search_fields = ('id', 'document__author__last_name', 'text')
    ordering_fields = '__all__'

    def get_queryset(self, *args, **kwargs):
        return Odoc.objects.all().select_related('document', 'document__author', 'odoc_type')


class OdocCreateAPIView(CreateAPIView):
    """
    API endpoint that odoc document to be updated.
    """
    queryset = Odoc.objects.all()
    serializer_class = OdocEditSerializer

    def perform_update(self, serializer):
        serializer.save(author=self.request.user)

    def perform_create(self, serializer):
        serializer.save(author=self.request.user)


class OdocDetailAPIView(RetrieveAPIView):
    """
    API endpoint that odoc document to be viewed.
    """
    queryset = Odoc.objects.all()
    serializer_class = OdocSerializer


class OdocUpdateAPIView(UpdateAPIView):
    """
    API endpoint that odoc document to be updated.
    """
    queryset = Odoc.objects.all()
    serializer_class = OdocEditSerializer


class OdocDeleteAPIView(DestroyAPIView):
    """
    API endpoint that odoc document to be deleted.
    """
    queryset = Odoc.objects.all()
    serializer_class = OdocSerializer

ais/odocs/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.urls import reverse_lazy
from django.views import generic

from .forms import OdocForm
from .models import Odoc


class CreateOdoc(LoginRequiredMixin, generic.CreateView):
    template_name = 'odocs/create_form.html'
    form_class = OdocForm

    def get_success_url(self):
        return reverse('odocs:edit', args=(self.object.id,))

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class ListOdoc(LoginRequiredMixin, generic.ListView):
    template_name = 'odocs/list_form.html'
    form_class = OdocForm
    model = Odoc
    # select_related = ('document',)

    def get_objects(self, queryset=None):
        return Odoc.objects.all().select_relate()


class EditOdoc(LoginRequiredMixin, generic.UpdateView):
    template_name = 'odocs/create_form.html'
    form_class = OdocForm

    def get_queryset(self):
        return Odoc.objects.all().select_related('document', 'document__author', 'odoc_type')

    def get_success_url(self):
        return reverse_lazy('odocs:list')


class DeleteOdoc(generic.DeleteView):
    model = Odoc
    success_url = reverse_lazy('odocs:list')

    def get(self, *args, **kwargs):
        """
        This has been overriden because by default
        DeleteView doesn't work with GET requests
        """
        return self.delete(*args, **kwargs)

ais/odocs/templates/odocs/_form.html
<form action="{% url 'odocs:create' %}" method="POST">
    {{ form.as_p }}
    {% csrf_token %}
<input type="submit" value="Сохранить" class="btn btn-primary">
</form>

ais/odocs/templates/odocs/create_form.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block title %} <a href="{%url 'odocs:list'%}">Служебная записка</a> {% endblock %}
{% block content %}
<div class="row">
<div class="container">
    <div class="row">
        <div class="col-md-4">
            {% if object.id %}
            <ul class="list-group">
                <li class="list-group-item list-group-item-info"> Автор: {{object.document.author}}</li>
                <li class="list-group-item list-group-item-info"> Создан: {{object.document.created_at| date:"d.m.Y H:i:s"}}</li>
                <li class="list-group-item list-group-item-info"> Изменен: {{object.document.changed_at |  date:"d.m.Y H:i:s"}}</li>
            </ul>
            {% endif %}
        </div>
        <div class="col-md-8">
            <form action="" method="POST">
                {% bootstrap_form form %}
                {% csrf_token %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">
                        {% bootstrap_icon "star" %} Сохранить
                    </button>
                    {% if object.id %}
                    <a href="{% url 'odocs:delete' object.id%}" class="btn btn-danger">
                        {% bootstrap_icon "trash" %} Удалить
                    </a>
                    {% endif %}
                {% endbuttons %}
            </form>
        </div>
    </div>
</div>
</div>
{%endblock%}

ais/odocs/templates/odocs/list_form.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block title %}
<a href="{% url 'dashboard' %}">Dashboard</a> 
{% endblock %}
{% block content%}
<div class="row" style="background: #eee">
        <a href="{% url 'odocs:create' %}" class="btn btn-primary">
            {% bootstrap_icon "plus" %} Добавить
        </a>
    </button>
</div>
<div class="row">
    <div class="content">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Автор</th>
                    <th>Дата создания</th>
                    <th>Тип документа</th>
                    <th>Текст</th>
                </tr>
            </thead>
            <tbody>
                {%for doc in object_list%}
                <tr>
                    <th scope="row">{{doc.id}}</th>
                    <td>{{doc.document.author.last_name}}</td>
                    <td>{{doc.document.created_at | date:"d.m.Y H:i:s" }}</td>
                    <td>{{doc.odoc_type.title}}</td>
                    <td><a href="{% url 'odocs:edit' doc.id%}">{{doc.text |safe | truncatechars_html:55}}</a></td>
                </tr>
                {%endfor%}
            </tbody>
        </table>
    </div>
</div>
{%endblock%}