ais/ais/urls.py
from django.conf import settings
from django.conf.urls import (
    url,
    include,
)
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

from profiles import urls as profiles_url
from odocs import urls as odocs_url
from dashboard.views import DashBoardView
from . import urls_api

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profiles/', include((profiles_url, 'profiles'), namespace='profiles')),
    url(r'^dashboard/$', DashBoardView.as_view(), name='dashboard'),
    url(r'^odocs/', include((odocs_url, 'odocs'), namespace='odocs')),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
    url(r'^api/', include((urls_api, 'api'), namespace='api')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

ais/dashboard/api/urls.py
from django.conf.urls import url, include
from rest_framework import routers

from . import views as views

urlpatterns = [
    url(r'^', views.OdocViewSet.as_view(), name='list'),
]

ais/dashboard/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url('^dashboard/$', views.DashBoardView.as_view(), name='dashboard'),
]

ais/dashboard/models.py
from django.db import models

# Create your models here.

ais/dashboard/forms.py
from django import forms

class DashBoardForm(forms.Form):
    pass

ais/dashboard/api/views.py
"""View for Dashboard"""
from rest_framework.generics import ListAPIView

from odocs.models import Odoc

from .serializers import OdocSerializer


class OdocViewSet(ListAPIView):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = Odoc.objects.all()
    serializer_class = OdocSerializer

ais/dashboard/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic

from .forms import DashBoardForm
from odocs.models import Odoc

class DashBoardView(LoginRequiredMixin, generic.ListView):
    form_class = DashBoardForm
    model = Odoc
    template_name = 'dashboard/dashboard.html'

    def get_objects(self, queryset=None):
        return Odoc.objects.all()

ais/dashboard/templates/dashboard/dashboard.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% block title %} <a href="#">Dashboard</a> {% endblock %}
{% block content %}
<div class="content">
    <div class="row">
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <img src="{% static 'png/document.jpg' %}" alt="Служебные записки">
                <div class="caption">
                    <h3>Служебные записки</h3>
                    <p>Документ общего вида!</p>
                    <p>
                        <a href="{% url 'odocs:list' %}" class="btn btn-primary" role="button">Открыть</a> 
                    </p>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <img src="{% static 'png/credit-card-851506_640.jpg' %}" alt="Заявки на оплату">
                <div class="caption">
                    <h3>Заявки на оплату</h3>
                    <p>В разработке...</p>
                    <p>
                        <a href="#" class="btn btn-primary disabled" role="button">Открыть</a>
                    </p>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <img src="{% static 'png/meeting.jpg' %}" alt="Контракты" style="max-height: 232px;">
                <div class="caption">
                    <h3>Контракты</h3>
                    <p>В разработке...</p>
                    <p><a href="#" class="btn btn-primary disabled" role="button">Открыть</a></p>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}