ais/ais/urls.py
from django.conf import settings
from django.conf.urls import (
    url,
    include,
)
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

from profiles import urls as profiles_url
from odocs import urls as odocs_url
from dashboard.views import DashBoardView
from . import urls_api

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profiles/', include((profiles_url, 'profiles'), namespace='profiles')),
    url(r'^dashboard/$', DashBoardView.as_view(), name='dashboard'),
    url(r'^odocs/', include((odocs_url, 'odocs'), namespace='odocs')),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'),
    url(r'^api/', include((urls_api, 'api'), namespace='api')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

ais/profiles/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url('^logout-confirm/$', views.LogoutView.as_view(), name='logout_confirm'),
    url('^logout/$', views.logout_view, name='logout'),
    url('^', include('django.contrib.auth.urls')),
]

ais/templates/base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <!--<link rel="icon" href="../../favicon.ico">-->

    <title>АИС 2.0</title>

    <link href="https://fonts.googleapis.com/css?family=Oxygen|Roboto" rel="stylesheet">
      <!-- Bootstrap core CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/ais.css' %}" rel="stylesheet">
   <!--  
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="{% static 'js/utils.js' %}"> </script>
    <script src="{% static 'js/dropzone.js' %}"></script> 
    -->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div id="wrapper" class="container">

      <!-- Static navbar -->
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{%url 'dashboard'%}">АИС 2.0</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="active">
                  {% block title %} <a href="#">Главная</a> {% endblock %}
              </li>
              <li><a href="#">О программе</a></li>
            </ul>
            {% if not user.is_authenticated %}
            <ul class="nav navbar-nav navbar-right">
              <li><a href="{%url 'profiles:login'%}">Войти</a></li>
              <li><a href="#">Регистрация</a></li>
            </ul>
            {% else %}
            <ul class="nav navbar-nav navbar-right">
              <li><a href="{% url 'profiles:logout' %}">Выйти</a></li>
            </ul>
            {% endif %}
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>
      <div id="content">
        {% block content %}{% endblock %}
      </div> 
      <!-- Main component for a primary marketing message or call to action -->
    </div> <!-- /container -->



    <!-- Bootstrap core JavaScript
    ==================================================-->  
    <!-- Placed at the end of the document so the pages load faster -->
    <script type="text/javascript" src="{% static "js/jquery-3.2.1.min.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>

  </body>
</html>

ais/templates/index.html
{% extends 'base.html' %} 
{% block title %} <a href="#">Главная</a> {% endblock %}
{% block content %}

{% endblock %}